<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <BaseOutputPath>$(SolutionDir)..\bin\web\</BaseOutputPath>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1901;NU1902;NU1903;NU1904;EXTEXP0018</WarningsNotAsErrors>
        <UserSecretsId>10a94da9-18ed-4c70-a9da-b461e08958c4</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <ContainerRepository>lumina-web</ContainerRepository>
        <DockerfileTag>lumina-web</DockerfileTag>
        <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\AssemblyInfo_Shared.cs" Link="Properties\AssemblyInfo_Shared.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints" />
        <PackageReference Include="FastEndpoints.Swagger" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
        <PackageReference Include="Microsoft.Extensions.Http.Polly" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
        <PackageReference Include="OpenTelemetry" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="Polly" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Enrichers.Span" />
        <PackageReference Include="Serilog.Settings.Configuration" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.File" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Core\Resources\Views\Admin\Plugins.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Plugins.resx</DependentUpon>
      </Compile>
      <Compile Update="Core\Resources\Views\Auth\ChangePassword.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>ChangePassword.resx</DependentUpon>
      </Compile>
      <Compile Update="Core\Resources\Views\Auth\Login.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Login.resx</DependentUpon>
      </Compile>
      <Compile Update="Core\Resources\Views\Auth\RecoverPassword.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>RecoverPassword.resx</DependentUpon>
      </Compile>
      <Compile Update="Core\Resources\Views\Auth\Register.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Register.resx</DependentUpon>
      </Compile>
      <Compile Update="Core\Resources\Views\Library\Management\Item.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Item.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Common\Middlewares\ExceptionHandlingMiddleware.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>ChangePassword.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\ChangePassword.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Login.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Login.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>RecoverPassword.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\RecoverPassword.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Register.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Auth\Register.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Item.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Library\Management\Item.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\Components\FileSystemBrowser\Default.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_Layout.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Shared\_NavMenu.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.de-DE.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.en-US.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.es-ES.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.fr-FR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.it-IT.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.ja-JP.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Plugins.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.ro-RO.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.uk-UA.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Core\Resources\Views\Admin\Plugins.zh-CN.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
    </ItemGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);TS6385</NoWarn>
    </PropertyGroup>
</Project>
