<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <BaseOutputPath>$(SolutionDir)..\bin\api\</BaseOutputPath>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\AssemblyInfo_Shared.cs" Link="Properties\AssemblyInfo_Shared.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DebounceThrottle" />
        <PackageReference Include="HtmlSanitizer" />
        <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
        <PackageReference Include="Microsoft.Extensions.ObjectPool" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Otp.NET" />
        <PackageReference Include="QRCoder" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
        <PackageReference Include="System.IO.Hashing" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.shared.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.shared.development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <DependentUpon>appsettings.shared.json</DependentUpon>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Lumina.Application\Lumina.Application.csproj" />
        <ProjectReference Include="..\Lumina.Plugins.Contracts\Lumina.Plugins.Contracts.csproj" />
    </ItemGroup>
</Project>
