POST {{host}}/api/v1/auth/change-password
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "username": "JohnDoe",
  "currentPassword": "Abcd123$",
  "newPassword": "123$Abcd",
  "newPasswordConfirm": "123$Abcd"
}
