POST {{host}}/api/v1/auth/change-password
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "Username": "JohnDoe",
  "CurrentPassword": "Abcd123$",
  "NewPassword": "123$Abcd",
  "NewPasswordConfirm": "123$Abcd"
}
