#region ========================================================================= USING =====================================================================================
using Bogus;
using Lumina.Presentation.Web.Common.DTO.Common;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
#endregion

namespace Lumina.Presentation.Web.Fixtures.Common.DTO.Common;

/// <summary>
/// Fixture class for the <see cref="ProblemDetailsDto"/> class.
/// </summary>
[ExcludeFromCodeCoverage]
public class ProblemDetailsDtoFixture
{
    private readonly Faker _faker = new();

    /// <summary>
    /// Creates a random valid <see cref="ProblemDetailsDto"/>.
    /// </summary>
    /// <param name="type">Optional. The URI reference that identifies the problem type.</param>
    /// <param name="title">Optional. A short, human-readable summary of the problem type.</param>
    /// <param name="status">Optional. The HTTP status code generated by the server.</param>
    /// <param name="detail">Optional. A detailed explanation specific to this occurrence of the problem.</param>
    /// <param name="instance">Optional. A URI reference that identifies the specific occurrence of the problem.</param>
    /// <returns>The created <see cref="ProblemDetailsDto"/>.</returns>
    public ProblemDetailsDto Create(
        string? type = null,
        string? title = null,
        int? status = null,
        string? detail = null,
        string? instance = null)
    {
        return new ProblemDetailsDto
        {
            Type = type ?? "https://tools.ietf.org/html/rfc4918#section-11.2",
            Title = title ?? _faker.Lorem.Word(),
            Status = status ?? _faker.Random.Int(400, 599),
            Detail = detail ?? _faker.Lorem.Sentence(),
            Instance = instance
        };
    }

    /// <summary>
    /// Creates a list of <see cref="ProblemDetailsDto"/> instances with randomized test data.
    /// </summary>
    /// <param name="count">Number of instances to create.</param>
    /// <returns>List of configured <see cref="ProblemDetailsDto"/> instances.</returns>
    public List<ProblemDetailsDto> CreateMany(int count = 3)
    {
        return [.. Enumerable.Range(0, count).Select(_ => Create())];
    }
}
