PUT {{host}}/api/v1/plugins/{{$guid}}/settings
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "pluginId": "{{$guid}}",
  "settings": {
    "BaseUrl": "https://musicbrainz.org/ws/2/",
    "SearchResultLimit": "25"
  }
}
