name: Run All Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore src/Lumina.sln
      - name: Build
        run: dotnet build src/Lumina.sln --no-restore
      - name: Run tests
        run: dotnet test src/Lumina.sln --no-build --verbosity normal
