name: Run All Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: # enable manual triggers

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/Lumina.sln
      - name: Build
        run: dotnet build src/Lumina.sln --no-restore
      - name: Run tests
        run: dotnet test src/Lumina.sln --no-build --verbosity normal